[package]
name = "tets2vox"
version = "0.1.0"
authors = ["Antonino Vacalebre"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"